# Generated by Django 3.0 on 2020-02-03 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tell', models.CharField(max_length=150)),
                ('birthday', models.DateTimeField()),
                ('img', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('madarek1', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('madarek2', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('madarek3', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ProfileDetail2User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
