# Generated by Django 3.0 on 2020-02-03 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shomare_yekta', models.IntegerField()),
                ('code_tafzili_shenavar', models.IntegerField(null=True)),
                ('name_tafzili_shenavar', models.CharField(max_length=110)),
                ('mande_hesab', models.DecimalField(decimal_places=1, max_digits=15)),
                ('tozihat_hesab', models.CharField(max_length=255)),
                ('tarikh_ijad', models.DateTimeField(auto_now_add=True)),
                ('tarikh_akharin_taghir', models.DateTimeField(auto_now=True)),
                ('tel1', models.CharField(max_length=20)),
                ('tel2', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=150)),
                ('Web', models.CharField(max_length=55)),
                ('addres1', models.CharField(max_length=190)),
                ('addres2', models.CharField(max_length=190)),
                ('shahr', models.CharField(max_length=40)),
                ('ostan', models.CharField(max_length=40)),
                ('code_posti', models.IntegerField(null=True)),
                ('keshvar', models.CharField(max_length=40)),
                ('code_eghtesadi', models.CharField(max_length=25)),
                ('telex', models.CharField(max_length=20)),
                ('onvan', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=30)),
                ('shomare_hesabe_banki1', models.CharField(max_length=40)),
                ('shomare_hesabe_banki2', models.CharField(max_length=40)),
                ('tarikh_tavalod', models.DateTimeField()),
                ('noe_hesab', models.CharField(max_length=30)),
                ('noe_kharidar_forooshande_dar_darayi', models.CharField(max_length=40)),
                ('code_meli', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DasteMahsool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeMahsool', models.IntegerField()),
                ('DasteMahsool', models.CharField(max_length=110)),
                ('VahedShomaresh', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeKala', models.IntegerField()),
                ('NameKala', models.CharField(max_length=140)),
                ('Vahed1', models.CharField(max_length=40)),
                ('Vahed2', models.CharField(max_length=40)),
                ('NameGorooheKalayi', models.CharField(max_length=140)),
                ('Gramazh', models.IntegerField()),
                ('ZaribeDoVahed', models.IntegerField(default=0)),
                ('Arz', models.IntegerField()),
                ('Tool', models.IntegerField()),
                ('CodeZirGorooheKalayi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Project', models.CharField(max_length=150)),
                ('NoeFactor', models.CharField(choices=[('R', 'رسمی'), ('G', 'غیر رسمی')], max_length=12)),
                ('Tirazh', models.IntegerField()),
                ('SharheMavadAvaliye1', models.CharField(max_length=300)),
                ('IsBehdashti', models.CharField(choices=[('B', 'بهداشتی'), ('G', 'غیر بهداشتی')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='WorkStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkStationName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastWork', models.TextField()),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_mahsool', models.IntegerField(null=True)),
                ('Code_ghalebe_asli', models.CharField(max_length=40)),
                ('Daste_mahsool', models.CharField(max_length=140)),
                ('Brand', models.CharField(choices=[('B', 'برونسی'), ('K', 'بلوکات')], max_length=10)),
                ('Name', models.CharField(max_length=25)),
                ('Material', models.CharField(max_length=140)),
                ('tool_arz_ertefa', models.CharField(max_length=50)),
                ('Formoole_name_mahsool', models.CharField(max_length=130)),
                ('Name_mahsoole_asli', models.CharField(max_length=100)),
                ('Toole_kaghaz', models.CharField(max_length=12)),
                ('Arze_kaghaz', models.CharField(max_length=12)),
                ('Boresh_pish_az_Chap', models.CharField(max_length=4)),
                ('Toole_Sheete_Chapi', models.CharField(max_length=12)),
                ('Arze_sheete_chapi', models.CharField(max_length=12)),
                ('Boresh_pas_az_chap', models.CharField(max_length=4)),
                ('Toole_varagh', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Arze_varagh', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Toole_single', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Arze_single', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Toole_maghzi', models.IntegerField(default=0, null=True)),
                ('Arze_maghzi', models.IntegerField(default=0, null=True)),
                ('toole_sheete_dicut', models.CharField(max_length=8)),
                ('arze_sheete_dicut', models.CharField(max_length=8)),
                ('dastgah_chap', models.CharField(max_length=20)),
                ('dastgah_dicut', models.CharField(max_length=10)),
                ('chasb', models.CharField(max_length=25)),
                ('baste_bandi', models.CharField(max_length=25)),
                ('tedad_dar_baste', models.IntegerField(null=True)),
                ('toole_tigh_be_tigh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('arze_tigh_be_tigh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('toole_mahsool', models.DecimalField(decimal_places=2, max_digits=5)),
                ('arze_mahsool', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ertefa_mahsool', models.DecimalField(decimal_places=2, max_digits=5)),
                ('toole_gostarde', models.DecimalField(decimal_places=2, max_digits=5)),
                ('arze_gostarde', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tedad_dar_ghaleb', models.IntegerField(null=True)),
                ('masahat_taki', models.CharField(max_length=35)),
                ('folder_link', models.CharField(max_length=100)),
                ('Name_mahsool', models.CharField(max_length=150)),
                ('Daste_mahsool_L', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.DasteMahsool')),
                ('Material_l', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Material')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='CodeGhaleb',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.Templates'),
        ),
        migrations.AddField(
            model_name='orders',
            name='Daste_Mahsool',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.DasteMahsool'),
        ),
        migrations.AddField(
            model_name='orders',
            name='MavadAvaliye1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.Material'),
        ),
        migrations.AddField(
            model_name='orders',
            name='Name_Moshtari',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.customers'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AttachmentFile', models.FileField(upload_to='media/% Y/% m/% d/')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Attachs2Order', to='orders.orders')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ws', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.WorkStations')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField()),
                ('R_S', models.CharField(choices=[('S', 'Send'), ('R', 'Receive')], max_length=10)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField()),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
