# Generated by Django 3.0 on 2019-12-28 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EsmeProject', models.CharField(max_length=300)),
                ('TooleJabeh', models.CharField(max_length=150)),
                ('ArzeJabeh', models.CharField(max_length=150)),
                ('ErtefaeJabeh', models.CharField(max_length=150)),
                ('TedadeRang', models.CharField(max_length=150)),
                ('NobateChap', models.CharField(choices=[('A', 'اول'), ('T', 'تکرار')], max_length=20)),
                ('NoeChap', models.CharField(choices=[('O', 'افست'), ('F', 'فلکسو'), ('LS', 'لمینیت '), ('LV', 'تکرار')], max_length=20)),
                ('MavadAvvaliye1', models.CharField(choices=[('T', 'تحریر'), ('G', 'گلاسه'), ('K', 'کرافت '), ('M', 'مومی'), ('PC', 'پشت چسبدار'), ('IB', 'ایندربرد'), ('PT', 'پشت طوسی '), ('D', 'دوپلکس'), ('V3', 'ورق 3 لایه'), ('V5', 'ورق 5 لایه'), ('TK', 'ترکیبی ')], max_length=20)),
                ('MavadAvvaliye2', models.CharField(choices=[('S', 'سینگل'), ('V', 'ورق')], max_length=20)),
                ('MavadAvvaliye3', models.CharField(choices=[('T', 'تحریر'), ('G', 'گلاسه'), ('K', 'کرافت '), ('M', 'مومی'), ('PC', 'پشت چسبدار'), ('IB', 'ایندربرد'), ('PT', 'پشت طوسی '), ('D', 'دوپلکس'), ('V3', 'ورق 3 لایه'), ('V5', 'ورق 5 لایه'), ('S', 'سینگل'), ('V', 'ورق')], max_length=20)),
                ('MavadAvvaliye4', models.CharField(choices=[('T', 'تحریر'), ('G', 'گلاسه'), ('K', 'کرافت '), ('M', 'مومی'), ('PC', 'پشت چسبدار'), ('IB', 'ایندربرد'), ('PT', 'پشت طوسی '), ('D', 'دوپلکس'), ('V3', 'ورق 3 لایه'), ('V5', 'ورق 5 لایه'), ('S', 'سینگل'), ('V', 'ورق')], max_length=20)),
                ('Behdashti', models.CharField(choices=[('O', 'بهداشتی'), ('F', 'غیر بهداشتی')], max_length=20)),
                ('Rol', models.CharField(choices=[('O', 'رول'), ('F', 'غیر رول')], max_length=20)),
                ('TarahiGraphici', models.CharField(choices=[('O', 'طراحی گرافیکی دارد'), ('F', 'طراحی گرافیکی ندارد')], max_length=20)),
                ('TarrahiStructure', models.CharField(choices=[('O', 'طراحی استراکچر دارد'), ('F', 'طراحی استراکچر ندارد')], max_length=20)),
                ('NemooneSazi', models.CharField(choices=[('O', 'نمونه سازی دارد'), ('F', 'نمونه سازی ندارد')], max_length=20)),
                ('Axasi', models.CharField(choices=[('O', 'عکاسی دارد'), ('F', 'عکاسی ندارد')], max_length=20)),
                ('Ghaleb', models.CharField(choices=[('O', 'قالب دارد'), ('F', 'قالب ندارد')], max_length=20)),
                ('NemooneMahsool', models.CharField(choices=[('O', 'نمونه محصول دارد'), ('F', 'نمونه محصول ندارد')], max_length=20)),
                ('NemooneBasteBandi', models.CharField(choices=[('O', 'نمونه بسته بندی دارد'), ('F', 'نمونه بسته بندی ندارد')], max_length=20)),
                ('Celiphone', models.CharField(choices=[('O', 'سلفون دارد'), ('F', 'سلفون ندارد')], max_length=20)),
                ('UV', models.CharField(choices=[('O', 'یو وی دارد'), ('F', 'یو وی ندارد')], max_length=20)),
                ('Verni', models.CharField(choices=[('O', 'ورنی دارد'), ('F', 'ورنی ندارد')], max_length=20)),
                ('TedadDarGhaleb', models.CharField(max_length=150)),
                ('SharheMavadAvaliye1', models.CharField(max_length=300)),
                ('SharheMavadAvaliye2', models.CharField(max_length=300)),
                ('SharheMavadAvaliye3', models.CharField(max_length=300)),
                ('SharheMavadAvaliye4', models.CharField(max_length=300)),
                ('ShomareSefaresh', models.CharField(max_length=30)),
                ('ArzeShitChapi', models.CharField(max_length=150)),
                ('TooleShitChapi', models.CharField(max_length=150)),
                ('ShomareHavale', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WorkStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkStationName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastWork', models.TextField()),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tell', models.CharField(max_length=150)),
                ('birthday', models.DateTimeField()),
                ('img', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('madarek1', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('madarek2', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('madarek3', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ProfileDetail2User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AttachmentFile', models.FileField(upload_to='media/% Y/% m/% d/')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Attachs2Order', to='orders.orders')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField()),
                ('R_S', models.CharField(choices=[('S', 'Send'), ('R', 'Receive')], max_length=10)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField()),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
