# Generated by Django 3.0 on 2020-02-08 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='NameMadareGoroohiyeKala',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='CodeGhaleb',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.Templates', verbose_name='کد قالب'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Daste_Mahsool',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.DasteMahsool', verbose_name='دسته محصول'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='IsBehdashti',
            field=models.CharField(choices=[('B', 'بهداشتی'), ('G', 'غیر بهداشتی')], max_length=12, verbose_name='بهداشتی یا غیر بهداشتی؟'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='MavadAvaliye1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.Material', verbose_name='مواد اولیه'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Name_Moshtari',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.customers', verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Name_Project',
            field=models.CharField(max_length=150, verbose_name='نام پروژه'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='NoeFactor',
            field=models.CharField(choices=[('R', 'رسمی'), ('G', 'غیر رسمی')], max_length=12, verbose_name='نوع فاکتور'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='SharheMavadAvaliye1',
            field=models.CharField(max_length=300, verbose_name='شرح مواد اولیه'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Tirazh',
            field=models.IntegerField(verbose_name='تیراژ'),
        ),
    ]
